# Generated by Django 3.0.3 on 2020-03-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField(max_length=20)),
                ('username', models.TextField(max_length=20)),
                ('email', models.TextField(max_length=20)),
                ('password', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=12)),
                ('permission', models.TextField(max_length=10)),
                ('usertype', models.TextField(max_length=10)),
            ],
        ),
    ]
