# Generated by Django 3.0.4 on 2020-03-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.TextField(max_length=5)),
                ('taskdes', models.TextField(max_length=100)),
                ('tasktype', models.TextField(max_length=10)),
                ('owner', models.TextField(max_length=15)),
                ('status', models.TextField(max_length=6)),
            ],
        ),
    ]
